name: NVolc
version: '${project.version}'
main: com.github.nindroida.nvolc.NVolc
api-version: '1.20'
commands:
  volc:
    description: Base command for NVolc
    usage: /volc
nvolc.*:
  description: Gives access to all NVolc commands
  default: op
  children:
    nvolc.main: true
nvolc.main:
  description: Allows the use of the `/volc` base command
  default: op
